language: cpp
compiler:
  - clang
env:
  global:
    - PATH=$HOME/miniconda3/bin:$HOME/miniconda3/envs/ci/bin/:$PATH
    - LD_LIBRARY_PATH=$HOME/miniconda3/lib/:$LD_LIBRARY_PATH 
    - LIBRARY_PATH=$HOME/miniconda3/lib/:$LIBRARY_PATH
    - OPENMM_PLUGIN_DIR=$HOME/miniconda3/lib/plugins
    - OPENMM_ROOT_DIR=$HOME/miniconda3
    - PYTHONPATH=$HOME/miniconda3/lib/python2.7/site-packages:$PYTHONPATH
    - OPENMM_INCLUDE_PATH=$HOME/miniconda3/include 
    - OPENMM_LIB_PATH=$HOME/miniconda3/lib/
    - CPLUS_INCLUDE_PATH=$HOME/miniconda3/include 
    - OPENMMDIR=$HOME/miniconda3/include 

before_install:
  - sudo apt-get update -qq
  - sudo add-apt-repository --yes ppa:kubuntu-ppa/backports 
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake
  - sudo apt-get install g++-4.6
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - bash Miniconda3-latest-Linux-x86_64.sh -b
  - PIP_ARGS="-U"
  - export PATH=$HOME/miniconda3/bin:$PATH
  - conda config --add channels http://conda.binstar.org/omnia
  - conda create --yes -n py3 python=3 --file requirements-conda.txt
  - source activate py3
  - $HOME/miniconda3/envs/py3/bin/pip install $PIP_ARGS nose-exclude
  - conda install --yes openmm runipy
  - if [ "$CC" = "gcc" ]; then export CC="gcc-4.6" CXX="g++-4.6"; fi
  
  - echo $PATH
  - echo $LD_LIBRARY_PATH
  - echo $LIBRARY_PATH
  - echo $OPENMM_PLUGIN_DIR
  - ls $OPENMM_ROOT_DIR
  - echo $PYTHONPATH
  - echo $OPENMM_INCLUDE_PATH
  - echo $OPENMM_LIB_PATH
  - echo $CPLUS_INCLUDE_PATH
  - echo $OPENMMDIR

install:
  - mkdir build
  - cd build
  - cmake -DSIRE_DISABLE_AVX=ON ../corelib
  - make -j 2
  - make install
