language: cpp
compiler:
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x -y
  - sudo apt-get update -qq
  - sudo apt-get install cmake
  - sudo apt-get install g++-4.6
#  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
#  - bash Miniconda3-latest-Linux-x86_64.sh -b
#  - PIP_ARGS="-U"
#  - export PATH=$HOME/miniconda3/bin:$PATH
#  - conda config --add channels http://conda.binstar.org/omnia
#  - conda create --yes -n py3 python=3 --file requirements-conda.txt
#  - source activate py3
#  - $HOME/miniconda3/envs/py3/bin/pip install $PIP_ARGS nose-exclude
#  - conda install --yes openmm runipy
  - if [ "$CC" = "gcc" ]; then export CC="gcc-4.6" CXX="g++-4.6"; fi

install:
  - mkdir build
  - cd build
  - cmake -DSIRE_DISABLE_AVX=ON ../corelib
  - make 
  - make install
