sudo: false

dist: precise
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7

addons:
  apt:
    sources: 
      - kubuntu-backports
    packages:
      - cmake
      - build-essential

before_install:
  - export NCORES=2
  - export SIRE_DONT_PHONEHOME=1
  - export INSTALL_SIRE_DIR=$HOME/sire.app

script:
  - bash compile_sire.sh
  - $HOME/sire.app/bin/sire_test

after_success:
  - echo "Time to go home and have a cup of tea! :)"
