language: cpp
compiler:
  - clang

before_install:
  - sudo add-apt-repository --yes ppa:smspillaz/cmake-2.8.12
  - sudo apt-get update -qq
  - sudo apt-get install cmake

script:
  - mkdir build
  - cd build
  - cmake -DSIRE_DISABLE_AVX=ON ../corelib
  - make -j 4
  - make install
