sudo: false

language: cpp
dist: trusty

before_install:
  - export NCORES=2
  - export SIRE_DONT_PHONEHOME=1
  - export INSTALL_SIRE_DIR=$HOME/sire.app

script:
  - bash compile_sire.sh
  - $HOME/sire.app/bin/sire_test

after_success:
  - echo "Time to go home and have a cup of tea! :)"
