language: cpp
compiler:
  - gcc
env:
  global:
    - PATH=$HOME/miniconda/bin:$PATH
    - LD_LIBRARY_PATH=$HOME/miniconda/lib/:$LD_LIBRARY_PATH 
    - LIBRARY_PATH=$HOME/miniconda/lib/:$LIBRARY_PATH
    - OPENMM_PLUGIN_DIR=$HOME/miniconda/lib/plugins
    - OPENMM_ROOT_DIR=$HOME/miniconda
    - PYTHONPATH=$HOME/miniconda/lib/python2.7/site-packages:$PYTHONPATH
    - OPENMM_INCLUDE_PATH=$HOME/miniconda/include 
    - OPENMM_LIB_PATH=$HOME/miniconda/lib/
    - CPLUS_INCLUDE_PATH=$HOME/miniconda/include 
    - OPENMMDIR=$HOME/miniconda/include 
    
before_install:
  - sudo apt-get update -qq
  - sudo add-apt-repository --yes ppa:kubuntu-ppa/backports 
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake
  - sudo apt-get install build-essential
  - sudo apt-get install libgtk2.0-dev 
  - sudo apt-get install libgl1-mesa-dev
  - sudo apt-get install g++-4.6
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - bash Miniconda-latest-Linux-x86_64.sh -b
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda config --add channels http://conda.binstar.org/omnia
  - conda install --yes openmm 
  - if [ "$CC" = "gcc" ]; then export CC="gcc-4.6" CXX="g++-4.6"; fi
  
  - echo $PATH
  - echo $LD_LIBRARY_PATH
  - echo $LIBRARY_PATH
  - ls $OPENMM_PLUGIN_DIR
  - ls $OPENMM_ROOT_DIR
  - echo $PYTHONPATH
  - ls $OPENMM_INCLUDE_PATH
  - ls $OPENMM_LIB_PATH
  - echo $CPLUS_INCLUDE_PATH
  - ls $OPENMMDIR

install:
  - mkdir build
  #- cd build
  #- cmake -DSIRE_DISABLE_AVX=ON ../corelib
  #- make -j 2

