language: cpp
compiler:
  - gcc

sudo: false

addons:
  apt:
    sources: 
      - kubuntu-backports
    packages:
      - cmake
      - build-essential
      - libgtk2.0-dev 
      - libgl1-mesa-dev

before_install:
  - export NCORES=1
  - export INSTALL_SIRE_DIR=$HOME/sire.app
  - if [ "$CC" = "gcc" ]; then export CC="gcc-4.6" CXX="g++-4.6"; fi

script:
  - bash compile_sire.sh

after_success:
  - echo "Time to go home and have a cup of tea! :)"
