language: c++
sudo: false

env:
  global:
    # variables used to control build of Sire - limit to 4 core build,
    # don't have Sire phone home (as would create false stats) and 
    # install into the home directory, sire.app
    - NCORES=4
    - SIRE_DONT_PHONEHOME=1
    - INSTALL_SIRE_DIR=$HOME/sire.app

  # Workaround for https://github.com/travis-ci/travis-ci/issues/4681
  matrix:
    - TRAVIS_EMPTY_JOB_WORKAROUND=true

addons:
  apt:
    packages:
      - g++-6
      - cmake
      - cmake-data
    sources: &sources
      - ubuntu-toolchain-r-test

matrix:
  exclude:
    - env: TRAVIS_EMPTY_JOB_WORKAROUND=true

  include:
    - os: osx
      osx_image: xcode8

   - os: linux
      env: COMPILER=g++-6 CC=gcc-6 CXX=g++-6
      compiler: gcc

  - os: linux
      env: LLVM_VERSION=default CC=clang CXX=clang++
      compiler: clang

script:
  - cmake --version
  - $CXX --version
  - which $CXX
  - bash compile_sire.sh
  - $HOME/sire.app/bin/sire_test

after_success:
  - echo "Congratulations - everything worked :-)"
