language: cpp
compiler:
  - gcc

sudo: required

addons:
  apt:
    packages:
      - build-essential

before_install:
  - export NCORES=1
  - export INSTALL_SIRE_DIR=$HOME/sire.app
  - sudo add-apt-repository --yes ppa:kalakris/cmake
  - sudo apt-get install cmake
  - if [ "$CC" = "gcc" ]; then export CC="gcc-4.6" CXX="g++-4.6"; fi

script:
  - bash compile_sire.sh

after_success:
  - echo "Time to go home and have a cup of tea! :)"
