language: cpp
compiler:
  - clang
# use travis-ci docker based infrastructure
sudo: false

cache:
  directories:
    - $HOME/.ccache

addons:
  apt:
    sources:
    - kubuntu-backports
    - llvm-toolchain-precise-3.5
    - ubuntu-toolchain-r-test
    packages:
    - autoconf
    - ccache
    - clang-3.5
    - cmake
    - g++-4.6

before_install:
- if [ "$CC" = "gcc" ]; then export CC="gcc-4.6" CXX="g++-4.6"; fi

install:
  - mkdir build
  - cd build
  - cmake -DSIRE_DISABLE_AVX=ON ../corelib
  - make 
  - make install
