language: cpp

compiler:
  - gcc
  - clang

dist: trusty

sudo: false

addons:
  apt:
    sources: 
      - kubuntu-backports
    packages:
      - cmake
      - build-essential
      - libgtk2.0-dev 
      - libgl1-mesa-dev

before_install:
  - export NCORES=2
  - export INSTALL_SIRE_DIR=$HOME/sire.app

script:
  - bash compile_sire.sh
  - $HOME/sire.app/bin/sire_test

after_success:
  - echo "Time to go home and have a cup of tea! :)"
