# Pipeline to build the latest version of Sire by starting from a docker
# image of a recent build. This avoids the (VERY) long build times if
# we start from scratch. You should ensure that 'sire-devel:latest' 
# corresponds to the right place to start...

trigger:
- devel

steps:
- script: |
    # compile from scratch (no docker with OS X)
    ./compile_sire.sh
  displayName: 'Build Sire'
- script: |
    # create the binary package before running tests, as the package must be clean
    $HOME/sire.app/bin/package_sire
  env:
    SIRE_RUN_FILE: $HOME/sire_devel_latest_osx.run
  displayName: 'Package Sire into a binary'
- script: |
    # now perform the tests
    $HOME/sire.app/bin/sire_test
  displayName: 'Run Sire tests'
- script: |
    # finally deploy the binary to an object store bucket identified by 'par_url'
    $HOME/sire.app/bin/conda install pycurl
    $HOME/sire.app/bin/python $HOME/Sire/docker/sire-deploy-devel/deploy.py $HOME/sire_devel_latest_osx.run
  env:
    par_url: $(parURL)
  displayName: 'Deploy binary to siremol.org'
