# Pipeline to build the latest version of Sire by starting from a docker
# image of a recent build. This avoids the (VERY) long build times if
# we start from scratch. You should ensure that 'sire-devel:latest' 
# corresponds to the right place to start...

trigger:
- devel

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    docker login -u $id -p $pswd
    docker pull siremol/sire-devel:latest
    docker tag siremol/sire-devel:latest siremol/sire-devel:last
    docker push siremol/sire-devel:last
    cd docker/sire-pipeline-devel && docker build -f Dockerfile -t siremol/sire-devel:latest .
    docker push siremol/sire-devel:latest
  env:
    pswd: $(dockerPassword)
    id: $(dockerId)
  displayName: 'Sire build'
