# Pipeline to build the latest version of Sire by starting from a docker
# image of a recent build. This avoids the (VERY) long build times if
# we start from scratch. You should ensure that 'sire-devel:latest' 
# corresponds to the right place to start...

trigger:
- devel

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'sire-devel-pipeline:latest'

steps:
- script: |
    cd docker/sire-pipeline-devel && docker build -f Dockerfile -t $(imageName) .
    docker login -u $id -p $pswd
    docker push siremol/$(imageName)
  env:
    pswd: $(dockerPassword)
    id: $(dockerId)
  displayName: 'Sire build'
