# Pipeline to build the latest version of Sire by starting from a docker
# image of a recent build. This avoids the (VERY) long build times if
# we start from scratch. You should ensure that 'sire-devel:latest' 
# corresponds to the right place to start...

trigger:
- devel

timeoutInMinutes: 120

steps:
- script: |
    ./compile_sire.sh --install $HOME/sire.app
  displayName: 'Build Sire'
- script: |
    # create the binary package before running tests, as the package must be clean
    $HOME/sire.app/bin/conda uninstall --yes cmake make clang_osx-64 clangxx_osx-64 llvm
    $HOME/sire.app/bin/conda clean -tipy
    $HOME/sire.app/bin/package_sire > package.log 2>&1
  env:
    SIRE_RUN_FILE: $HOME/sire_devel_latest_osx.run
  displayName: 'Package Sire into a binary'
- script: |
    # finally deploy the binary to an object store bucket identified by 'par_url'
    $HOME/sire.app/bin/conda install -y pycurl
    $HOME/sire.app/bin/python docker/sire-deploy-devel/deploy.py $HOME/sire_devel_latest_osx.run
  env:
    PAR_URL: $(parURL)
  displayName: 'Deploy binary to siremol.org'
